import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { dirname } from "node:path";
import type {
  OpenDesignAuthenticatorEntry,
  OpenDesignAuthenticatorHistoryFilter,
  OpenDesignAuthenticatorHistoryRecord,
  OpenDesignAuthenticatorRegistration,
  OpenDesignAuthenticatorQrRequest,
  OpenDesignAuthenticatorResult,
  OpenDesignAuthenticatorView,
  OpenDesignHostAuthenticator,
} from "@open-design/host";
import { AuthenticatorStore, type AuthenticatorMetadataStore } from "./store.js";
import { buildOtpauthUri, decodeBase32, encodeLocalQr, parseOtpauthUri, totp } from "./protocol.js";
import { ElectronSecretVault, type SafeStorageAdapter } from "./electron-vault.js";
import { LocalGitHistory, PasswordProtectedHistory } from "./history.js";
import { SuperConfirmationVerifier } from "./super-confirmation.js";

class JsonMetadata implements AuthenticatorMetadataStore {
  readonly #path: string;
  constructor(path: string) { this.#path = path; }
  async read() { try { return JSON.parse(await readFile(this.#path, "utf8")) as OpenDesignAuthenticatorEntry[]; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return []; throw error; } }
  async write(entries: OpenDesignAuthenticatorEntry[]) { await mkdir(dirname(this.#path), { recursive: true }); const temp = `${this.#path}.${randomUUID()}.tmp`; await writeFile(temp, JSON.stringify(entries) + "\n", "utf8"); await rename(temp, this.#path); }
}

const unavailable = <T>(reason: string, code: Extract<OpenDesignAuthenticatorResult<never>, { ok: false }>["code"] = "unavailable"): OpenDesignAuthenticatorResult<T> => ({ ok: false, code, reason });
const success = <T>(value: T): OpenDesignAuthenticatorResult<T> => ({ ok: true, ...value });

export class DesktopAuthenticatorHost implements OpenDesignHostAuthenticator {
  readonly #vault: ElectronSecretVault;
  readonly #metadata: JsonMetadata;
  readonly #now: () => number;
  readonly #history: LocalGitHistory;
  #historyManager: PasswordProtectedHistory | null = null;
  #retention: "keep-all" | "30-days" | "90-days" = "keep-all";
  readonly #confirmation = new SuperConfirmationVerifier();
  #store: Promise<AuthenticatorStore> | null = null;
  constructor(options: { directory: string; safeStorage: SafeStorageAdapter; now?: () => number }) { this.#vault = new ElectronSecretVault({ directory: `${options.directory}/vault`, safeStorage: options.safeStorage }); this.#metadata = new JsonMetadata(`${options.directory}/entries.json`); this.#now = options.now ?? Date.now; this.#historyDirectoryValue = `${options.directory}/history`; this.#history = new LocalGitHistory({ directory: this.#historyDirectoryValue, vault: this.#vault }); }
  vaultStatus(): Promise<{ available: boolean; reason?: string }> { return Promise.resolve(this.#vault.isAvailable() ? { available: true } : { available: false, reason: "The operating-system credential vault is unavailable." }); }
  async list(query?: string): Promise<OpenDesignAuthenticatorResult<{ entries: OpenDesignAuthenticatorEntry[] }>> { try { return success({ entries: (await this.store()).list(query) }); } catch { return unavailable("Authenticator metadata could not be read.", "persistence-failed"); } }
  async view(id: string, trustedNowMs?: number): Promise<OpenDesignAuthenticatorResult<{ entry: OpenDesignAuthenticatorView }>> { try { const entry = (await this.store()).list().find((candidate) => candidate.id === id); if (!entry) return unavailable("Authenticator entry was not found.", "not-found"); const secret = await (await this.store()).secret(id); const parameters = { secret, algorithm: entry.algorithm, digits: entry.digits, period: entry.period } as const; const now = this.#now(); return success({ entry: { ...entry, currentCode: groupCode(totp(parameters, now)), nextCode: groupCode(totp(parameters, (Math.floor(now / 1000 / entry.period) + 1) * entry.period * 1000)), secondsRemaining: entry.period - (Math.floor(now / 1000) % entry.period), clockWarning: trustedNowMs !== undefined && Math.abs(now - trustedNowMs) > 90_000 ? `Clock differs from the trusted reference by ${Math.round((now - trustedNowMs) / 1000)} seconds.` : null } }); } catch { return unavailable("Authenticator entry could not be read from the operating-system vault.", "vault-unavailable"); } }
  async register(input: OpenDesignAuthenticatorRegistration): Promise<OpenDesignAuthenticatorResult<{ entry: OpenDesignAuthenticatorEntry }>> { if (!this.#vault.isAvailable()) return unavailable("The operating-system credential vault is unavailable.", "vault-unavailable"); if (!input || typeof input !== "object" || typeof input.kind !== "string") return unavailable("Authenticator registration input is invalid.", "invalid-input"); try { const parameters = input.kind === "manual" ? { issuer: input.issuer, account: input.account, secret: decodeBase32(input.secretBase32), algorithm: input.algorithm ?? "SHA-1", digits: input.digits ?? 6, period: input.period ?? 30 } : input.kind === "otpauth-uri" ? parseOtpauthUri(input.value) : null; if (!parameters) return unavailable("QR image, clipboard, and camera decoding are unavailable until a bounded local decoder is connected."); const current = totp(parameters, this.#now()); if (input.confirmationCode !== current) return unavailable("Registration requires one current authenticator code before the entry is armed.", "confirmation-required"); return success({ entry: await (await this.store()).add(parameters) }); } catch (error) { return unavailable(error instanceof Error ? error.message : "Authenticator registration failed.", "invalid-input"); } }
  async qrFor(input: OpenDesignAuthenticatorQrRequest): Promise<OpenDesignAuthenticatorResult<{ uri: string; version: 5 | 6; size: 37 | 41; modules: readonly (readonly boolean[])[] }>> { if (!this.#vault.isAvailable()) return unavailable("The operating-system credential vault is unavailable.", "vault-unavailable"); try { const parameters = { issuer: input.issuer, account: input.account, secret: decodeBase32(input.secretBase32), algorithm: input.algorithm ?? "SHA-1", digits: input.digits ?? 6, period: input.period ?? 30 } as const; const uri = buildOtpauthUri(parameters); const matrix = encodeLocalQr(uri); return success({ uri, ...matrix }); } catch (error) { return unavailable(error instanceof Error ? error.message : "Local QR generation failed.", "invalid-input"); } }
  async reorder(ids: readonly string[]): Promise<OpenDesignAuthenticatorResult> { try { await (await this.store()).reorder(ids); return success({}); } catch { return unavailable("Authenticator order could not be saved.", "persistence-failed"); } }
  async setGroup(ids: readonly string[], group: string | null): Promise<OpenDesignAuthenticatorResult> { try { await (await this.store()).setGroup(ids, group); return success({}); } catch { return unavailable("Authenticator groups could not be saved.", "persistence-failed"); } }
  issueSuperConfirmation(action: string, ids: readonly string[]): Promise<OpenDesignAuthenticatorResult<{ confirmationToken: string }>> { try { return Promise.resolve(success({ confirmationToken: this.#confirmation.issue(action, ids) })); } catch { return Promise.resolve(unavailable("Confirmation scope is invalid.", "invalid-input")); } }
  async remove(ids: readonly string[], confirmationToken: string): Promise<OpenDesignAuthenticatorResult> { if (!this.#confirmation.consume(confirmationToken, "remove authenticator entries", ids)) return unavailable("Removing authenticator entries requires the in-app super confirmation.", "super-confirmation-required"); try { await (await this.store()).remove(ids); return success({}); } catch { return unavailable("Authenticator entries could not be removed.", "persistence-failed"); } }
  async historyUnlock(password: string): Promise<OpenDesignAuthenticatorResult> { if (!password || password.length > 512) return unavailable("History password is empty or exceeds the bounded length.", "invalid-input"); try { await this.#history.init(); try { this.#historyManager = await PasswordProtectedHistory.open(`${this.#historyDirectory()}`, this.#vault, password); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; this.#historyManager = await PasswordProtectedHistory.create(this.#historyDirectory(), this.#vault, password); } return success({}); } catch { return unavailable("History manager could not be unlocked.", "history-locked"); } }
  async historyList(filter?: OpenDesignAuthenticatorHistoryFilter): Promise<OpenDesignAuthenticatorResult<{ records: OpenDesignAuthenticatorHistoryRecord[] }>> { if (!this.#historyManager) return unavailable("History manager authentication is required.", "history-locked"); try { const records = (await this.#historyManager.records()).filter((record) => { const haystack = `${record.action} ${record.createdAt}`.toLocaleLowerCase(); const query = filter?.query?.trim().toLocaleLowerCase() ?? ""; const from = filter?.fromDate ? Date.parse(filter.fromDate) : Number.NEGATIVE_INFINITY; const to = filter?.toDate ? Date.parse(`${filter.toDate}T23:59:59.999Z`) : Number.POSITIVE_INFINITY; const actions = new Set(filter?.actions ?? []); const time = Date.parse(record.createdAt); return (!query || haystack.includes(query)) && (!actions.size || actions.has(record.action)) && time >= from && time <= to; }).map((record) => ({ id: record.id, action: record.action, createdAt: record.createdAt, summary: `Authenticator ${record.action}` })); return success({ records }); } catch { return unavailable("History records could not be read.", "persistence-failed"); } }
  async historyDiff(id: string): Promise<OpenDesignAuthenticatorResult<{ diff: string }>> { if (!this.#historyManager) return unavailable("History manager authentication is required.", "history-locked"); try { const record = (await this.#historyManager.records()).find((candidate) => candidate.id === id); if (!record) return unavailable("History record was not found.", "not-found"); return success({ diff: JSON.stringify(await this.#historyManager.restore(record), null, 2) }); } catch { return unavailable("History diff could not be read.", "persistence-failed"); } }
  async historyRestore(id: string): Promise<OpenDesignAuthenticatorResult> { if (!this.#historyManager) return unavailable("History manager authentication is required.", "history-locked"); try { const record = (await this.#historyManager.records()).find((candidate) => candidate.id === id); if (!record) return unavailable("History record was not found.", "not-found"); await this.#history.append("restored", await this.#historyManager.restore(record)); return success({}); } catch { return unavailable("History restore could not be recorded.", "persistence-failed"); } }
  async historySetRetention(retention: "keep-all" | "30-days" | "90-days"): Promise<OpenDesignAuthenticatorResult> { if (!this.#historyManager) return unavailable("History manager authentication is required.", "history-locked"); if (!["keep-all", "30-days", "90-days"].includes(retention)) return unavailable("History retention is invalid.", "invalid-input"); this.#retention = retention; return success({}); }
  async historyExportRedacted(filter?: OpenDesignAuthenticatorHistoryFilter): Promise<OpenDesignAuthenticatorResult<{ content: string }>> { const listed = await this.historyList(filter); if (!listed.ok) return listed; return success({ content: JSON.stringify({ version: 1, retention: this.#retention, secretsOmitted: true, records: listed.records }, null, 2) }); }
  historyExportSensitive(_filter: OpenDesignAuthenticatorHistoryFilter | undefined, confirmationToken: string): Promise<OpenDesignAuthenticatorResult<{ content: string }>> { if (!this.#confirmation.consume(confirmationToken, "export sensitive authenticator history", [])) return Promise.resolve(unavailable("Sensitive history export requires the real in-app super confirmation.", "super-confirmation-required")); return Promise.resolve(unavailable("Sensitive history export is not available until the protected history manager is unlocked.", "history-locked")); }
  #storeReady(): Promise<AuthenticatorStore> { return this.#store ??= AuthenticatorStore.open({ metadata: this.#metadata, vault: this.#vault, history: this.#history }); }
  #historyDirectory(): string { return this.#historyDirectoryValue; }
  readonly #historyDirectoryValue: string;
  private store(): Promise<AuthenticatorStore> { return this.#storeReady(); }
}

function groupCode(value: string): string { return value.match(/.{1,3}/g)?.join(" ") ?? value; }
