import { mkdtempSync, rmSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  assertDesktopScaffoldCollisions,
  claimDesktopProjectDirectory,
  createDesktopScaffoldFiles,
  createDesktopStarterFiles,
  desktopScaffoldState,
  materializeDesktopScaffoldProject,
  removeDesktopScaffoldClaim,
  desktopScaffoldTestHooks,
} from '../src/desktop-scaffold.js';

describe('desktop application scaffold service', () => {
  it('creates project-specific starter and secure shell files from one state revision', () => {
    const state = desktopScaffoldState({ entryFile: 'index.html', revision: 3 });
    const files = createDesktopScaffoldFiles({
      projectName: 'Orders Desk',
      projectId: 'orders-desk',
      entryFile: 'index.html',
      revision: 3,
    });
    const starter = createDesktopStarterFiles('Orders Desk');
    expect(state.revision).toBe(3);
    expect(state.files).toMatchObject({
      entry: 'index.html',
      styles: 'styles.css',
      script: 'app.js',
      package: 'desktop/package.json',
    });
    expect(files.map((file) => file.role)).toEqual([
      'readme', 'package', 'config', 'main', 'preload', 'renderer',
    ]);
    expect(starter.map((file) => file.path)).toEqual(['index.html', 'styles.css', 'app.js']);
    const main = files.find((file) => file.role === 'main')?.body ?? '';
    expect(main).toContain('contextIsolation: true');
    expect(main).toContain('nodeIntegration: false');
    expect(main).toContain('sandbox: true');
    expect(main).toContain('will-attach-webview');
    expect(main).toContain('setWindowOpenHandler');
    expect(main).toContain('canonicalPath');
    expect(main).toContain('realpathSync.native');
    expect(main).toContain('parsed.protocol !== \'file:\'');
    expect(main).not.toMatch(/[A-Z]:\\|\/Users\//);
  });

  it('rejects absolute, escaping, and non-HTML entry files', () => {
    for (const entryFile of ['/index.html', '../index.html', 'C:/index.html', 'index.js']) {
      expect(() => createDesktopScaffoldFiles({
        projectName: 'Safe project',
        entryFile,
      })).toThrow();
    }
  });

  it('rejects case-insensitive generated path collisions before writing', () => {
    expect(() => assertDesktopScaffoldCollisions([
      { relPath: 'Desktop/PACKAGE.JSON' },
    ])).toThrow(/desktop scaffold path already exists/i);
  });

  it('claims an empty project, validates every generated byte, and leaves a recoverable marker', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'od-desktop-scaffold-'));
    try {
      const claim = await claimDesktopProjectDirectory(root, 'orders-desk');
      const result = await materializeDesktopScaffoldProject({
        projectDir: claim.projectDir,
        projectId: 'orders-desk',
        projectName: 'Orders Desk',
        ownerNonce: claim.ownerNonce,
      });
      expect(result.claim.state).toBe('ready');
      expect(JSON.parse(await readFile(path.join(claim.projectDir, '.desktop-scaffold-claim.json'), 'utf8')).files).toHaveProperty('index.html');
      expect(await readFile(path.join(claim.projectDir, 'index.html'), 'utf8')).toContain('Orders Desk');
      expect(await readFile(path.join(claim.projectDir, 'desktop', 'package.json'), 'utf8')).toContain('material-designer-orders-desk');
      await removeDesktopScaffoldClaim(claim.projectDir, claim.ownerNonce);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('refuses a pre-existing directory before writing or deleting its files', async () => {
    const root = mkdtempSync(path.join(tmpdir(), 'od-desktop-scaffold-collision-'));
    try {
      const existing = path.join(root, 'orders-desk');
      await mkdir(existing, { recursive: true });
      await writeFile(path.join(existing, 'keep.txt'), 'keep me');
      await expect(claimDesktopProjectDirectory(root, 'orders-desk')).rejects.toMatchObject({ code: 'EEXIST' });
      expect(await readFile(path.join(existing, 'keep.txt'), 'utf8')).toBe('keep me');
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  it('cleans the exact owned claim after an interruption at every generated file boundary', async () => {
    const generated = Object.values({
      entry: 'index.html',
      styles: 'styles.css',
      script: 'app.js',
      package: 'desktop/package.json',
      main: 'desktop/src/main.cjs',
      preload: 'desktop/src/preload.cjs',
      renderer: 'desktop/src/renderer.js',
      config: 'desktop/desktop-scaffold.json',
      readme: 'desktop/README.md',
    });
    for (const interruptedPath of generated) {
      const root = mkdtempSync(path.join(tmpdir(), 'od-desktop-scaffold-interrupt-'));
      desktopScaffoldTestHooks.beforeFileWrite = (relativePath) => {
        if (relativePath === interruptedPath) throw new Error(`interrupted at ${relativePath}`);
      };
      try {
        const claim = await claimDesktopProjectDirectory(root, `interrupt-${generated.indexOf(interruptedPath)}`);
        await expect(materializeDesktopScaffoldProject({
          projectDir: claim.projectDir,
          projectId: `interrupt-${generated.indexOf(interruptedPath)}`,
          projectName: 'Interrupted project',
          ownerNonce: claim.ownerNonce,
        })).rejects.toThrow(/interrupted/);
        await expect(readFile(claim.projectDir, 'utf8')).rejects.toBeTruthy();
      } finally {
        desktopScaffoldTestHooks.beforeFileWrite = null;
        rmSync(root, { recursive: true, force: true });
      }
    }
  });
});
