/**
 * Acknowledgement bridge for appearance mutations.
 *
 * The payload is deliberately metadata only. It identifies the stable domain,
 * element or property, action, and client revision key. Style snapshots,
 * credential material, source paths, and rendered values never cross this
 * boundary.
 */

export interface AppearanceHistoryMutation {
  readonly domainId: string;
  readonly targetId: string;
  readonly action: string;
  /** Stable client idempotency key, generated by the appearance store. */
  readonly revisionId: string;
}

export interface AppearanceHistoryAcknowledgement {
  readonly acknowledged: true;
  readonly duplicate: boolean;
  readonly historyRevisionId: string;
}

export const APPEARANCE_HISTORY_TIMEOUT_MS = 10_000;

function validField(value: string): boolean {
  return value.length > 0
    && value.length <= 128
    && !/[\u0000-\u001f\u007f]/u.test(value)
    && !value.includes('/')
    && !value.includes('\\');
}

function validateMutation(input: AppearanceHistoryMutation): boolean {
  return validField(input.domainId)
    && /^[a-z0-9._-]+$/u.test(input.domainId)
    && validField(input.targetId)
    && /^[A-Za-z0-9:._-]+$/u.test(input.targetId)
    && validField(input.action)
    && /^[A-Za-z0-9 .:_-]+$/u.test(input.action)
    && validField(input.revisionId);
}

/**
 * Send a bounded acknowledgement and reject on timeout or malformed success.
 * Callers should treat a rejection as an unacknowledged history write and
 * preserve the appearance edit while surfacing recovery at its origin.
 */
export async function acknowledgeAppearanceMutation(
  input: AppearanceHistoryMutation,
): Promise<AppearanceHistoryAcknowledgement> {
  if (!validateMutation(input)) {
    throw new Error('invalid appearance history mutation metadata');
  }
  const controller = new AbortController();
  let timedOut = false;
  const timer = globalThis.setTimeout(() => {
    timedOut = true;
    controller.abort();
  }, APPEARANCE_HISTORY_TIMEOUT_MS);
  try {
    const response = await fetch('/api/history/mutation', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify(input),
      signal: controller.signal,
    });
    if (!response.ok) {
      throw new Error(`appearance history acknowledgement refused (${response.status})`);
    }
    const payload: unknown = await response.json();
    if (
      typeof payload !== 'object'
      || payload === null
      || (payload as Record<string, unknown>).acknowledged !== true
      || typeof (payload as Record<string, unknown>).duplicate !== 'boolean'
      || typeof (payload as Record<string, unknown>).historyRevisionId !== 'string'
      || !(payload as Record<string, unknown>).historyRevisionId
    ) {
      throw new Error('appearance history acknowledgement was malformed');
    }
    return payload as AppearanceHistoryAcknowledgement;
  } catch (error) {
    if (timedOut) throw new Error(`appearance history acknowledgement timed out after ${APPEARANCE_HISTORY_TIMEOUT_MS} ms`);
    throw error;
  } finally {
    globalThis.clearTimeout(timer);
  }
}
