[CmdletBinding()]
param(
  [string]$RepoRoot = '',
  [string]$SourcePath = '',
  [string]$RootOutput = '',
  [string]$SiteOutput = ''
)

$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($RepoRoot)) { $RepoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..')) }

if ([string]::IsNullOrWhiteSpace($SourcePath)) { $SourcePath = Join-Path $RepoRoot 'assets/screenshots/home-windows.png' }
if ([string]::IsNullOrWhiteSpace($RootOutput)) { $RootOutput = Join-Path $RepoRoot 'social-preview.png' }
if ([string]::IsNullOrWhiteSpace($SiteOutput)) { $SiteOutput = Join-Path $RepoRoot 'site/assets/social-preview.png' }

if (-not (Test-Path -LiteralPath $SourcePath -PathType Leaf)) {
  throw "The genuine source capture is missing: $SourcePath"
}

$bytes = [System.IO.File]::ReadAllBytes($SourcePath)
$pngSignature = [byte[]](137,80,78,71,13,10,26,10)
if ($bytes.Length -lt $pngSignature.Length) {
  throw "The social-preview source is not a PNG with a valid signature: $SourcePath"
}
for ($i = 0; $i -lt $pngSignature.Length; $i++) {
  if ($bytes[$i] -ne $pngSignature[$i]) {
    throw "The social-preview source is not a PNG with a valid signature: $SourcePath"
  }
}

foreach ($destination in @($RootOutput, $SiteOutput)) {
  $parent = Split-Path -Parent $destination
  if (-not (Test-Path -LiteralPath $parent -PathType Container)) {
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
  }
  [System.IO.File]::WriteAllBytes($destination, $bytes)
}

$sourceHash = (Get-FileHash -LiteralPath $SourcePath -Algorithm SHA256).Hash.ToLowerInvariant()
$rootHash = (Get-FileHash -LiteralPath $RootOutput -Algorithm SHA256).Hash.ToLowerInvariant()
$siteHash = (Get-FileHash -LiteralPath $SiteOutput -Algorithm SHA256).Hash.ToLowerInvariant()
if ($sourceHash -ne $rootHash -or $sourceHash -ne $siteHash) {
  throw "Social preview copies are not byte-identical. Source $sourceHash, root $rootHash, served $siteHash."
}

Write-Output "PASS: generated byte-identical social previews from $SourcePath"
Write-Output "SHA256: $sourceHash"
