#!/usr/bin/env node
/**
 * scripts/line-count.mjs — the committed line counter for this repository.
 *
 * This is the script CI runs at the released commit; its table is what goes into
 * the release notes. It exists so the figure is produced the same way every time,
 * by a program anyone can read, rather than by a hand-typed number that drifts.
 *
 * Design rules this script follows:
 *
 *   - File discovery is `git ls-files`, so untracked build output can never be
 *     counted. Nothing is discovered by walking the filesystem.
 *   - Every tracked file lands in exactly one row. There is a mandatory
 *     "Uncategorized" catch-all in each scope, and a self-check that the rows sum
 *     back to the tracked-file count. A bucketing that loses files misrepresents
 *     the project.
 *   - Excluded paths are printed as visible rows with their own numbers, never
 *     silently dropped.
 *   - The imported upstream tree (`design/`) is reported separately from this
 *     repository's own code, and the totals are labelled so a reader can see both
 *     what the project is and what the repository holds.
 *   - Authorship is attributed per SURVIVING line with `git blame`, never by
 *     summing added lines from the log. It is opt-in behind `--blame` because it
 *     spawns one `git blame` per file.
 *   - The attribution total must equal the counted line total for the same scope.
 *     If they disagree the script fails loudly instead of printing two numbers
 *     that contradict each other.
 *
 * No dependencies outside node: builtins. Node ESM.
 *
 * Usage:
 *   node scripts/line-count.mjs
 *   node scripts/line-count.mjs --json
 *   node scripts/line-count.mjs --blame
 *   node scripts/line-count.mjs --blame --blame-paths 'scripts/**,mockups/**'
 */

import { execFileSync } from 'node:child_process';
import { readFileSync, writeSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/**
 * Path prefixes holding an imported upstream tree. Files under these prefixes are
 * counted, but reported in their own scope: they are not code written for this
 * repository. Keep the trailing slash.
 */
const UPSTREAM_PREFIXES = [{ prefix: 'design/', label: 'Imported upstream tree (`design/`)' }];

/**
 * Directory names that mark vendored, dependency, or build-output trees. A tracked
 * file whose path contains one of these segments is excluded from the line counts
 * and reported as an excluded row instead. (`git ls-files` already keeps untracked
 * build output out; this catches the rare case of one being committed.)
 */
const EXCLUDED_DIR_SEGMENTS = new Set([
  '.git',
  'node_modules',
  'vendor',
  'third_party',
  'third-party',
  'dist',
  '.next',
  '.turbo',
  '.astro',
  '.output',
  '.cache',
  'coverage',
]);

/** Directory names that make a file a test file. */
const TEST_DIR_SEGMENTS = new Set(['tests', 'test', '__tests__', 'e2e', 'spec', '__snapshots__']);

/** Directory names that make a file generated. */
const GENERATED_DIR_SEGMENTS = new Set(['generated', '__generated__', 'gen']);

/** Lockfiles are generated by a package manager, not written by hand. */
const LOCKFILE_BASENAMES = new Set([
  'pnpm-lock.yaml',
  'package-lock.json',
  'npm-shrinkwrap.json',
  'yarn.lock',
  'bun.lock',
  'bun.lockb',
  'Cargo.lock',
  'poetry.lock',
  'composer.lock',
  'Gemfile.lock',
  'go.sum',
  'flake.lock',
  'uv.lock',
  'pdm.lock',
]);

/** Markers a file may use in its opening lines to declare itself generated. */
const GENERATED_MARKERS = [
  /@generated\b/,
  /\bdo not edit\b/i,
  /\bcode generated by\b/i,
  /\bauto-?generated\b/i,
  /\bgenerated (?:from|by)\b/i,
];

/** Extensions whose contents are binary; never read, never line-counted. */
const BINARY_EXTENSIONS = new Set([
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'ico', 'icns', 'bmp', 'tif', 'tiff',
  'mp4', 'webm', 'mov', 'avi', 'mkv', 'mp3', 'wav', 'ogg', 'flac', 'm4a',
  'ttf', 'otf', 'woff', 'woff2', 'eot',
  'zip', 'gz', 'tgz', 'bz2', 'xz', '7z', 'rar', 'tar',
  'pdf', 'wasm', 'bin', 'exe', 'dll', 'so', 'dylib', 'node', 'class', 'jar',
  'db', 'sqlite', 'sqlite3', 'psd', 'ai', 'sketch', 'fig', 'blend',
]);

/** Extension → language/kind label, and the category that extension implies. */
const EXTENSION_KINDS = new Map(Object.entries({
  // --- source ---------------------------------------------------------------
  ts: ['Source', 'TypeScript'],
  mts: ['Source', 'TypeScript'],
  cts: ['Source', 'TypeScript'],
  tsx: ['Source', 'TypeScript (TSX)'],
  js: ['Source', 'JavaScript'],
  mjs: ['Source', 'JavaScript'],
  cjs: ['Source', 'JavaScript'],
  jsx: ['Source', 'JavaScript (JSX)'],
  vue: ['Source', 'Vue'],
  svelte: ['Source', 'Svelte'],
  astro: ['Source', 'Astro'],
  py: ['Source', 'Python'],
  rb: ['Source', 'Ruby'],
  go: ['Source', 'Go'],
  rs: ['Source', 'Rust'],
  java: ['Source', 'Java'],
  kt: ['Source', 'Kotlin'],
  kts: ['Source', 'Kotlin'],
  swift: ['Source', 'Swift'],
  c: ['Source', 'C'],
  h: ['Source', 'C/C++ header'],
  hh: ['Source', 'C++ header'],
  hpp: ['Source', 'C++ header'],
  cc: ['Source', 'C++'],
  cpp: ['Source', 'C++'],
  cxx: ['Source', 'C++'],
  cs: ['Source', 'C#'],
  php: ['Source', 'PHP'],
  lua: ['Source', 'Lua'],
  pl: ['Source', 'Perl'],
  r: ['Source', 'R'],
  dart: ['Source', 'Dart'],
  scala: ['Source', 'Scala'],
  ex: ['Source', 'Elixir'],
  exs: ['Source', 'Elixir'],
  sh: ['Source', 'Shell'],
  bash: ['Source', 'Shell'],
  zsh: ['Source', 'Shell'],
  fish: ['Source', 'Shell'],
  ps1: ['Source', 'PowerShell'],
  psm1: ['Source', 'PowerShell'],
  bat: ['Source', 'Batch'],
  cmd: ['Source', 'Batch'],
  sql: ['Source', 'SQL'],
  proto: ['Source', 'Protocol Buffers'],
  graphql: ['Source', 'GraphQL'],
  gql: ['Source', 'GraphQL'],
  prisma: ['Source', 'Prisma'],
  nix: ['Source', 'Nix'],

  // --- styles and markup ----------------------------------------------------
  css: ['Styles & markup', 'CSS'],
  scss: ['Styles & markup', 'Sass (SCSS)'],
  sass: ['Styles & markup', 'Sass'],
  less: ['Styles & markup', 'Less'],
  styl: ['Styles & markup', 'Stylus'],
  html: ['Styles & markup', 'HTML'],
  htm: ['Styles & markup', 'HTML'],
  ejs: ['Styles & markup', 'HTML template'],
  hbs: ['Styles & markup', 'Handlebars'],
  pug: ['Styles & markup', 'Pug'],

  // --- configuration --------------------------------------------------------
  yml: ['Configuration', 'YAML'],
  yaml: ['Configuration', 'YAML'],
  toml: ['Configuration', 'TOML'],
  ini: ['Configuration', 'INI'],
  cfg: ['Configuration', 'INI'],
  conf: ['Configuration', 'Config'],
  properties: ['Configuration', 'Properties'],
  env: ['Configuration', 'Environment file'],

  // --- documentation --------------------------------------------------------
  md: ['Documentation', 'Markdown'],
  mdx: ['Documentation', 'MDX'],
  markdown: ['Documentation', 'Markdown'],
  mdc: ['Documentation', 'Markdown'],
  rst: ['Documentation', 'reStructuredText'],
  adoc: ['Documentation', 'AsciiDoc'],

  // --- data and assets ------------------------------------------------------
  json: ['Data & assets', 'JSON'],
  json5: ['Data & assets', 'JSON'],
  jsonl: ['Data & assets', 'JSON Lines'],
  ndjson: ['Data & assets', 'JSON Lines'],
  jsonc: ['Data & assets', 'JSON'],
  csv: ['Data & assets', 'CSV'],
  tsv: ['Data & assets', 'TSV'],
  xml: ['Data & assets', 'XML'],
  svg: ['Data & assets', 'SVG'],
  txt: ['Data & assets', 'Plain text'],
  patch: ['Data & assets', 'Patch'],
  diff: ['Data & assets', 'Patch'],
  ipynb: ['Data & assets', 'Notebook'],
}));

/** Extensionless or dotted basenames with a fixed classification. */
const BASENAME_KINDS = new Map(Object.entries({
  '.gitignore': ['Configuration', 'Git config'],
  '.gitattributes': ['Configuration', 'Git config'],
  '.gitmodules': ['Configuration', 'Git config'],
  '.gitkeep': ['Configuration', 'Git config'],
  '.dockerignore': ['Configuration', 'Docker config'],
  '.npmrc': ['Configuration', 'Package manager config'],
  '.nvmrc': ['Configuration', 'Toolchain pin'],
  '.node-version': ['Configuration', 'Toolchain pin'],
  '.tool-versions': ['Configuration', 'Toolchain pin'],
  '.editorconfig': ['Configuration', 'Editor config'],
  '.browserslistrc': ['Configuration', 'Build config'],
  'Dockerfile': ['Configuration', 'Dockerfile'],
  'Makefile': ['Configuration', 'Makefile'],
  'CODEOWNERS': ['Configuration', 'Repository policy'],
  'LICENSE': ['Documentation', 'Licence'],
  'LICENCE': ['Documentation', 'Licence'],
  'NOTICE': ['Documentation', 'Licence notice'],
  'AUTHORS': ['Documentation', 'Plain text'],
}));

/** `.json` files whose basename means configuration rather than data. */
const JSON_CONFIG_BASENAMES = new Set([
  'package.json',
  'jsconfig.json',
  'turbo.json',
  'biome.json',
  'nest-cli.json',
  'vercel.json',
  'netlify.json',
  'components.json',
  'renovate.json',
  '.eslintrc.json',
  '.prettierrc.json',
  '.babelrc.json',
  '.markdownlint.json',
]);

/** Path segments that get a two-level area label (e.g. `apps/daemon`). */
const AREA_DEPTH_TWO = new Set(['apps', 'packages', 'tools', 'plugins', 'modules', 'services']);

/** Fixed row order so two runs of the script produce comparable tables. */
const CATEGORY_ORDER = [
  'Source',
  'Tests',
  'Styles & markup',
  'Configuration',
  'Documentation',
  'Generated',
  'Data & assets',
  'Uncategorized',
];

/**
 * Automation-identity pattern. A commit counts as agent-authored when this matches
 * the author name or the author email, or when it matches the value of a
 * `Co-Authored-By:` trailer in the commit message. The pattern is printed in the
 * output so the number can be checked against the rule that produced it.
 */
const AGENT_IDENTITY_RE =
  /\b(?:bot|claude|codex|opencode|copilot|cursor|devin|aider|jules|gemini|chatgpt|openai|anthropic|agent|automation|github-actions|dependabot|renovate|semantic-release)\b|\[bot\]/i;

/** `Co-Authored-By:` trailer, anywhere in a commit message. */
const COAUTHOR_TRAILER_RE = /^[ \t]*Co-Authored-By:[ \t]*(.+)$/gim;

/** The all-zero object id `git blame` reports for lines not yet committed. */
const UNCOMMITTED_SHA_RE = /^0+$/;

// ---------------------------------------------------------------------------
// Small utilities
// ---------------------------------------------------------------------------

const SCRIPT_REL_FALLBACK = 'scripts/line-count.mjs';

/**
 * Print a message and exit with a non-zero status.
 *
 * The write is synchronous. `process.exit()` discards pending asynchronous
 * writes, and on POSIX a piped stderr — which is what continuous integration
 * hands this script — is asynchronous. The two messages that matter most here
 * are also the longest ones (the accounting self-check and the attribution
 * invariant, both of which list offending files), so an asynchronous write is
 * exactly where the explanation would be truncated or lost. `writeSync` can
 * still throw EAGAIN on a non-blocking pipe; fall back rather than exit mute.
 */
function fail(message, code = 2) {
  const text = `line-count: ${message}\n`;
  try {
    writeSync(2, text);
  } catch {
    process.stderr.write(text);
  }
  process.exit(code);
}

/** Run git and return its stdout. */
function git(args, { cwd, encoding = 'utf8' } = {}) {
  return execFileSync('git', args, {
    cwd,
    encoding,
    windowsHide: true,
    maxBuffer: 512 * 1024 * 1024,
  });
}

/** Format an integer with thousands separators, deterministically. */
function num(n) {
  return String(n).replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

/** Share of a total, as a string. Returns '—' when the total is zero. */
function share(part, total) {
  if (!total) return '—';
  return `${((part / total) * 100).toFixed(1)}%`;
}

/** Lowercase extension without the dot, or '' when there is none. */
function extensionOf(basename) {
  const dot = basename.lastIndexOf('.');
  if (dot <= 0) return ''; // no dot, or a dotfile such as `.npmrc`
  return basename.slice(dot + 1).toLowerCase();
}

/**
 * Count lines the way `git blame` does: a trailing newline does not open a new
 * line, and an empty file has zero lines. Blank lines are lines that are empty
 * once whitespace (including a trailing CR) is removed.
 */
function countLines(text) {
  if (text === '') return { lines: 0, nonBlank: 0 };
  const parts = text.split('\n');
  if (parts[parts.length - 1] === '') parts.pop();
  let nonBlank = 0;
  for (const line of parts) {
    if (line.trim() !== '') nonBlank++;
  }
  return { lines: parts.length, nonBlank };
}

/**
 * Minimal glob → RegExp for `--blame-paths`. Supports `**`, `*`, `?`, `{a,b}` and
 * character classes. Anything else is matched literally.
 */
function globToRegExp(glob) {
  let out = '';
  let i = 0;
  const escape = (ch) => ch.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  while (i < glob.length) {
    const ch = glob[i];
    if (ch === '*') {
      if (glob[i + 1] === '*') {
        if (glob[i + 2] === '/') {
          out += '(?:.*/)?';
          i += 3;
        } else {
          out += '.*';
          i += 2;
        }
        continue;
      }
      out += '[^/]*';
      i += 1;
      continue;
    }
    if (ch === '?') {
      out += '[^/]';
      i += 1;
      continue;
    }
    if (ch === '{') {
      const end = glob.indexOf('}', i);
      if (end !== -1) {
        const alts = glob
          .slice(i + 1, end)
          .split(',')
          .map((part) => part.split('').map(escape).join(''));
        out += `(?:${alts.join('|')})`;
        i = end + 1;
        continue;
      }
    }
    if (ch === '[') {
      const end = glob.indexOf(']', i + 1);
      if (end !== -1) {
        out += glob.slice(i, end + 1);
        i = end + 1;
        continue;
      }
    }
    out += escape(ch);
    i += 1;
  }
  return new RegExp(`^${out}$`);
}

/**
 * Build a path matcher from a list of globs. A pattern with no wildcard also
 * matches everything beneath it, so `--blame-paths scripts` scopes to that
 * directory as a reader would expect.
 */
function buildPathMatcher(globs) {
  if (globs.length === 0) return null;
  const matchers = globs.map((glob) => {
    const re = globToRegExp(glob);
    const plainPrefix = /[*?{[\]]/.test(glob) ? null : glob.replace(/\/+$/, '') + '/';
    return (file) => re.test(file) || (plainPrefix !== null && file.startsWith(plainPrefix));
  });
  return (file) => matchers.some((m) => m(file));
}

// ---------------------------------------------------------------------------
// Classification
// ---------------------------------------------------------------------------

/** Does any path segment (excluding the basename) match the given set? */
function hasDirSegment(file, set) {
  const parts = file.split('/');
  for (let i = 0; i < parts.length - 1; i++) {
    if (set.has(parts[i])) return true;
  }
  return false;
}

/** The first excluded directory segment in a path, or null. */
function excludedSegment(file) {
  const parts = file.split('/');
  for (let i = 0; i < parts.length - 1; i++) {
    if (EXCLUDED_DIR_SEGMENTS.has(parts[i])) return parts[i];
  }
  return null;
}

/** Kind label plus the category the extension implies, for one file. */
function kindOf(file) {
  const basename = file.slice(file.lastIndexOf('/') + 1);
  const byBasename = BASENAME_KINDS.get(basename);
  if (byBasename) return { category: byBasename[0], kind: byBasename[1] };

  const ext = extensionOf(basename);

  // Config-shaped JSON is configuration; every other .json is data.
  if (ext === 'json') {
    if (
      JSON_CONFIG_BASENAMES.has(basename) ||
      /^tsconfig(\..+)?\.json$/.test(basename) ||
      /\.config\.json$/.test(basename)
    ) {
      return { category: 'Configuration', kind: 'JSON (config)' };
    }
  }

  // Dockerfile.web, Makefile.common, .env.example and friends.
  if (/^Dockerfile\./.test(basename)) return { category: 'Configuration', kind: 'Dockerfile' };
  if (/^Makefile\./.test(basename)) return { category: 'Configuration', kind: 'Makefile' };
  if (/^\.env(\..+)?$/.test(basename)) return { category: 'Configuration', kind: 'Environment file' };
  if (/^\.(eslintrc|prettierrc|babelrc|stylelintrc)(\..+)?$/.test(basename)) {
    return { category: 'Configuration', kind: 'Tooling config' };
  }
  if (/^(README|CHANGELOG|CONTRIBUTING|HANDOFF|ROADMAP|SECURITY|AGENTS)$/.test(basename)) {
    return { category: 'Documentation', kind: 'Plain text' };
  }

  const byExt = ext ? EXTENSION_KINDS.get(ext) : undefined;
  if (byExt) return { category: byExt[0], kind: byExt[1] };

  // Catch-all. The label keeps the extension so the row is actionable.
  return { category: 'Uncategorized', kind: ext ? `Other (.${ext})` : 'Other (no extension)' };
}

/** Does the opening of a text file declare that it is generated? */
function declaresGenerated(text) {
  const head = text.slice(0, 2048).split('\n').slice(0, 5).join('\n');
  return GENERATED_MARKERS.some((re) => re.test(head));
}

/**
 * Final category for a file. Generated wins over tests, tests win over the
 * extension's own category, so a generated fixture is never counted as
 * hand-written test code.
 */
function categoryOf(file, extensionCategory, isGeneratedByContent) {
  const basename = file.slice(file.lastIndexOf('/') + 1);
  if (
    isGeneratedByContent ||
    LOCKFILE_BASENAMES.has(basename) ||
    hasDirSegment(file, GENERATED_DIR_SEGMENTS)
  ) {
    return 'Generated';
  }
  if (
    hasDirSegment(file, TEST_DIR_SEGMENTS) ||
    /\.(test|spec)\.[^.]+$/.test(basename) ||
    /^(vitest|jest|playwright)\.config\.[^.]+$/.test(basename)
  ) {
    return 'Tests';
  }
  return extensionCategory;
}

/** Subproject label for a file, relative to its scope prefix. */
function areaOf(file, scopePrefix) {
  let rel = file;
  if (scopePrefix && rel.startsWith(scopePrefix)) rel = rel.slice(scopePrefix.length);
  const parts = rel.split('/');
  if (parts.length === 1) return '(root)';
  if (AREA_DEPTH_TWO.has(parts[0]) && parts.length > 2) return `${parts[0]}/${parts[1]}`;
  return parts[0];
}

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

const HELP = `line-count.mjs — count the lines of this repository, by category and by authorship.

Usage:
  node ${SCRIPT_REL_FALLBACK} [options]

Options:
  --json                  Emit JSON instead of a Markdown table.
  --markdown              Emit the Markdown table (default).
  --blame                 Attribute every surviving line with \`git blame\`.
                          Spawns one \`git blame\` per file; scope it with
                          --blame-paths on a large tree.
  --blame-paths <globs>   Comma-separated globs limiting which files are blamed.
                          Implies --blame. Supports **, *, ?, {a,b} and [a-z].
  -h, --help              Show this message.

File discovery is \`git ls-files\`, so untracked build output is never counted.`;

function parseArgs(argv) {
  const opts = { json: false, blame: false, blamePaths: [], help: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === '--json') {
      opts.json = true;
    } else if (arg === '--markdown' || arg === '--md') {
      opts.json = false;
    } else if (arg === '--blame') {
      opts.blame = true;
    } else if (arg === '--blame-paths') {
      const value = argv[++i];
      if (value === undefined) fail('--blame-paths requires a glob argument');
      opts.blamePaths.push(...value.split(',').map((s) => s.trim()).filter(Boolean));
      opts.blame = true;
    } else if (arg.startsWith('--blame-paths=')) {
      const value = arg.slice('--blame-paths='.length);
      opts.blamePaths.push(...value.split(',').map((s) => s.trim()).filter(Boolean));
      opts.blame = true;
    } else if (arg === '-h' || arg === '--help') {
      opts.help = true;
    } else {
      fail(`unknown argument: ${arg}\n\n${HELP}`);
    }
  }
  return opts;
}

// ---------------------------------------------------------------------------
// Collection
// ---------------------------------------------------------------------------

/** Parse `git ls-files -s -z` into one entry per tracked path. */
function listTrackedFiles(repoRoot) {
  const raw = execFileSync('git', ['ls-files', '-s', '-z'], {
    cwd: repoRoot,
    windowsHide: true,
    maxBuffer: 512 * 1024 * 1024,
  });
  const seen = new Map();
  let start = 0;
  for (let i = 0; i < raw.length; i++) {
    if (raw[i] !== 0) continue;
    const record = raw.toString('utf8', start, i);
    start = i + 1;
    if (!record) continue;
    const tab = record.indexOf('\t');
    if (tab === -1) continue;
    const meta = record.slice(0, tab).split(' ');
    const file = record.slice(tab + 1);
    // Merge-conflict stages repeat a path; count it once.
    if (!seen.has(file)) seen.set(file, { mode: meta[0], oid: meta[1], path: file });
  }
  return [...seen.values()];
}

/** Which reported scope a file belongs to. */
function scopeOf(file) {
  for (const upstream of UPSTREAM_PREFIXES) {
    if (file.startsWith(upstream.prefix)) return upstream.prefix;
  }
  return '';
}

/**
 * Read and classify every tracked file.
 * Returns counted rows per scope, excluded rows, and the per-file records the
 * blame pass needs.
 */
function collect(repoRoot, entries) {
  /** @type {Map<string, {scope:string, category:string, kind:string, files:number, lines:number, nonBlank:number}>} */
  const rows = new Map();
  /** @type {Map<string, {scope:string, area:string, files:number, lines:number, nonBlank:number}>} */
  const areas = new Map();
  /** @type {Map<string, {reason:string, files:number, lines:number, nonBlank:number, linesKnown:boolean, examples:string[]}>} */
  const excluded = new Map();
  /** @type {{path:string, scope:string, lines:number}[]} */
  const counted = [];
  const uncategorizedPaths = [];

  const addRow = (scope, category, kind, lines, nonBlank) => {
    const key = `${scope}\u0000${category}\u0000${kind}`;
    let row = rows.get(key);
    if (!row) {
      row = { scope, category, kind, files: 0, lines: 0, nonBlank: 0 };
      rows.set(key, row);
    }
    row.files += 1;
    row.lines += lines;
    row.nonBlank += nonBlank;
  };

  const addArea = (scope, area, lines, nonBlank) => {
    const key = `${scope}\u0000${area}`;
    let row = areas.get(key);
    if (!row) {
      row = { scope, area, files: 0, lines: 0, nonBlank: 0 };
      areas.set(key, row);
    }
    row.files += 1;
    row.lines += lines;
    row.nonBlank += nonBlank;
  };

  const addExcluded = (reason, file, linesKnown, lines, nonBlank) => {
    let row = excluded.get(reason);
    if (!row) {
      row = { reason, files: 0, lines: 0, nonBlank: 0, linesKnown, examples: [] };
      excluded.set(reason, row);
    }
    row.files += 1;
    if (linesKnown) {
      row.lines += lines;
      row.nonBlank += nonBlank;
    } else {
      row.linesKnown = false;
    }
    if (row.examples.length < 3) row.examples.push(file);
  };

  for (const entry of entries) {
    const file = entry.path;

    // Gitlinks (submodules) and symlinks hold no lines of this repository's code.
    if (entry.mode === '160000') {
      addExcluded('Submodule reference (gitlink)', file, false, 0, 0);
      continue;
    }
    if (entry.mode === '120000') {
      addExcluded('Symbolic link', file, false, 0, 0);
      continue;
    }

    const vendored = excludedSegment(file);
    const basename = file.slice(file.lastIndexOf('/') + 1);
    const ext = extensionOf(basename);

    if (BINARY_EXTENSIONS.has(ext)) {
      addExcluded('Binary file (not text)', file, false, 0, 0);
      continue;
    }

    let buffer;
    try {
      buffer = readFileSync(path.join(repoRoot, file));
    } catch (err) {
      if (err && (err.code === 'ENOENT' || err.code === 'EISDIR')) {
        // Tracked but absent from the working tree (sparse checkout, or a
        // submodule whose contents were never initialised). Reported, not dropped.
        addExcluded('Tracked but missing from the working tree', file, false, 0, 0);
        continue;
      }
      throw err;
    }

    if (buffer.subarray(0, 8000).includes(0)) {
      addExcluded('Binary file (not text)', file, false, 0, 0);
      continue;
    }

    const text = buffer.toString('utf8');
    const { lines, nonBlank } = countLines(text);

    if (vendored) {
      addExcluded(`Vendored or build-output path (\`${vendored}/\`)`, file, true, lines, nonBlank);
      continue;
    }

    const scope = scopeOf(file);
    const { category: extCategory, kind } = kindOf(file);
    const category = categoryOf(file, extCategory, declaresGenerated(text));

    addRow(scope, category, kind, lines, nonBlank);
    addArea(scope, areaOf(file, scope), lines, nonBlank);
    counted.push({ path: file, scope, lines });
    if (category === 'Uncategorized') uncategorizedPaths.push(file);
  }

  return { rows: [...rows.values()], areas: [...areas.values()], excluded: [...excluded.values()], counted, uncategorizedPaths };
}

// ---------------------------------------------------------------------------
// Authorship attribution
// ---------------------------------------------------------------------------

/**
 * Classify a commit as agent- or human-authored. The result is cached because a
 * blame run over a large tree revisits the same commits thousands of times.
 */
function makeCommitClassifier(repoRoot) {
  const cache = new Map();
  return function classify(sha) {
    if (cache.has(sha)) return cache.get(sha);
    let out;
    try {
      out = git(['show', '-s', '--no-patch', '--format=%an%x00%ae%x00%B', sha], { cwd: repoRoot });
    } catch {
      // A commit that cannot be read is reported as unclassified rather than
      // guessed at; the caller surfaces the count.
      const unknown = { agent: false, unclassified: true, reason: 'commit could not be read' };
      cache.set(sha, unknown);
      return unknown;
    }
    const [name = '', email = '', body = ''] = out.split('\u0000');
    let agent = AGENT_IDENTITY_RE.test(name) || AGENT_IDENTITY_RE.test(email);
    let reason = agent ? 'author identity matches the automation pattern' : '';
    if (!agent) {
      COAUTHOR_TRAILER_RE.lastIndex = 0;
      let match;
      while ((match = COAUTHOR_TRAILER_RE.exec(body)) !== null) {
        if (AGENT_IDENTITY_RE.test(match[1])) {
          agent = true;
          reason = 'Co-Authored-By trailer names an agent';
          break;
        }
      }
    }
    const result = { agent, unclassified: false, reason: reason || 'no automation signal' };
    cache.set(sha, result);
    return result;
  };
}

/**
 * Sum blamed lines per commit for one file, using `git blame --incremental`
 * (header blocks are emitted once per commit; every group carries its line count).
 */
function blameFile(repoRoot, file) {
  const out = git(['blame', '--incremental', '--', file], { cwd: repoRoot });
  const perSha = new Map();
  let total = 0;
  for (const line of out.split('\n')) {
    // `\r?` because git on some platforms terminates lines with CRLF.
    const m = /^([0-9a-f]{40,64}) \d+ \d+ (\d+)\r?$/.exec(line);
    if (!m) continue;
    const sha = m[1];
    const n = Number(m[2]);
    perSha.set(sha, (perSha.get(sha) ?? 0) + n);
    total += n;
  }
  return { perSha, total };
}

/**
 * Attribute every surviving line in scope. Fails loudly if the attribution total
 * and the counted line total disagree — two contradictory numbers in one table
 * destroy the credibility of both.
 */
function attribute(repoRoot, counted, matcher) {
  const files = counted.filter((f) => (matcher ? matcher(f.path) : true));
  const classify = makeCommitClassifier(repoRoot);
  const totals = { agent: 0, human: 0, uncommitted: 0, unclassified: 0 };
  const mismatches = [];
  const failures = [];
  let attributedTotal = 0;
  let countedTotal = 0;
  let done = 0;
  const isTty = Boolean(process.stderr.isTTY);
  let lastTick = 0;

  process.stderr.write(
    `line-count: attributing ${num(files.length)} file(s) with git blame; this spawns one blame per file\n`,
  );

  for (const record of files) {
    countedTotal += record.lines;
    if (record.lines > 0) {
      let result;
      try {
        result = blameFile(repoRoot, record.path);
      } catch (err) {
        failures.push(`${record.path}: ${err && err.message ? err.message.split('\n')[0] : String(err)}`);
        done++;
        continue;
      }
      if (result.total !== record.lines) {
        mismatches.push(`${record.path}: counted ${record.lines}, blamed ${result.total}`);
      }
      attributedTotal += result.total;
      for (const [sha, n] of result.perSha) {
        if (UNCOMMITTED_SHA_RE.test(sha)) {
          totals.uncommitted += n;
          continue;
        }
        const info = classify(sha);
        if (info.unclassified) totals.unclassified += n;
        else if (info.agent) totals.agent += n;
        else totals.human += n;
      }
    }
    done++;
    const now = Date.now();
    if (now - lastTick > 500 || done === files.length) {
      lastTick = now;
      const message = `line-count: blame ${num(done)}/${num(files.length)} files`;
      if (isTty) process.stderr.write(`\r${message}   `);
      else if (done % 250 === 0 || done === files.length) process.stderr.write(`${message}\n`);
    }
  }
  if (isTty) process.stderr.write('\n');

  if (failures.length) {
    fail(
      `git blame failed on ${failures.length} file(s); attribution is incomplete and is not reported.\n  ` +
        failures.slice(0, 10).join('\n  '),
      1,
    );
  }
  if (attributedTotal !== countedTotal) {
    fail(
      `attribution total (${num(attributedTotal)}) does not equal the counted line total for the same scope ` +
        `(${num(countedTotal)}).\n` +
        `The usual cause is counting a file's trailing newline as an extra line, which git blame does not.\n` +
        `First mismatching files:\n  ${
          mismatches.length ? mismatches.slice(0, 10).join('\n  ') : '(no per-file mismatch was recorded)'
        }`,
      1,
    );
  }

  return {
    computed: true,
    scope: matcher ? 'files matching --blame-paths' : 'every counted file',
    files: files.length,
    lines: attributedTotal,
    agent: totals.agent,
    human: totals.human,
    uncommitted: totals.uncommitted,
    unclassified: totals.unclassified,
  };
}

// ---------------------------------------------------------------------------
// Aggregation and rendering
// ---------------------------------------------------------------------------

/** Sum a list of rows. */
function sum(rows) {
  return rows.reduce(
    (acc, row) => ({
      files: acc.files + row.files,
      lines: acc.lines + row.lines,
      nonBlank: acc.nonBlank + row.nonBlank,
    }),
    { files: 0, lines: 0, nonBlank: 0 },
  );
}

/** Category order first, then lines descending, then kind — stable across runs. */
function sortRows(rows) {
  return [...rows].sort((a, b) => {
    const ca = CATEGORY_ORDER.indexOf(a.category);
    const cb = CATEGORY_ORDER.indexOf(b.category);
    if (ca !== cb) return ca - cb;
    if (b.lines !== a.lines) return b.lines - a.lines;
    return a.kind.localeCompare(b.kind);
  });
}

/** Render a GitHub-flavoured Markdown table. */
function mdTable(headers, aligns, rows) {
  const sep = aligns.map((a) => (a === 'r' ? '---:' : a === 'c' ? ':---:' : '---'));
  const lines = [`| ${headers.join(' | ')} |`, `| ${sep.join(' | ')} |`];
  for (const row of rows) lines.push(`| ${row.join(' | ')} |`);
  return lines.join('\n');
}

function scopeTable(rows) {
  const sorted = sortRows(rows);
  const body = sorted.map((r) => [r.category, r.kind, num(r.files), num(r.lines), num(r.nonBlank)]);
  const total = sum(sorted);
  body.push(['**Total**', '', `**${num(total.files)}**`, `**${num(total.lines)}**`, `**${num(total.nonBlank)}**`]);
  return mdTable(['Category', 'Kind', 'Files', 'Lines', 'Non-blank'], ['l', 'l', 'r', 'r', 'r'], body);
}

function areaTable(rows) {
  const sorted = [...rows].sort((a, b) => (b.lines !== a.lines ? b.lines - a.lines : a.area.localeCompare(b.area)));
  const body = sorted.map((r) => [`\`${r.area}\``, num(r.files), num(r.lines), num(r.nonBlank)]);
  return mdTable(['Area', 'Files', 'Lines', 'Non-blank'], ['l', 'r', 'r', 'r'], body);
}

function renderMarkdown(report) {
  const out = [];
  const { scopes, excluded, totals, attribution, meta } = report;

  out.push('### Line count');
  out.push('');
  out.push(
    `Commit \`${meta.commitShort}\` · tracked files only (\`git ls-files\`), read from the working tree.`,
  );
  if (meta.workingTreeDirty) {
    out.push('');
    out.push(
      '> [!NOTE]',
      '> The working tree had uncommitted changes when this ran, so the counts describe the working tree rather than the commit alone.',
    );
  }
  out.push('');

  for (const scope of scopes) {
    out.push(`#### ${scope.label}`);
    out.push('');
    out.push(scopeTable(scope.rows));
    out.push('');
    if (scope.areas.length > 1) {
      out.push('<details>');
      out.push(`<summary>${scope.label} — the same lines split by subproject</summary>`);
      out.push('');
      out.push(areaTable(scope.areas));
      out.push('');
      out.push('</details>');
      out.push('');
    }
  }

  out.push('#### Excluded from the counts above');
  out.push('');
  if (excluded.length === 0) {
    out.push('No tracked file was excluded.');
  } else {
    const body = excluded.map((r) => [
      r.reason,
      num(r.files),
      r.linesKnown ? num(r.lines) : 'n/a',
      r.linesKnown ? num(r.nonBlank) : 'n/a',
      r.examples.map((e) => `\`${e}\``).join(', ') + (r.files > r.examples.length ? ', …' : ''),
    ]);
    out.push(mdTable(['Excluded', 'Files', 'Lines', 'Non-blank', 'Examples'], ['l', 'r', 'r', 'r', 'l'], body));
  }
  out.push('');

  out.push('#### Totals');
  out.push('');
  out.push(
    mdTable(
      ['Scope', 'Files', 'Lines', 'Non-blank'],
      ['l', 'r', 'r', 'r'],
      [
        [
          totals.own.label,
          num(totals.own.files),
          num(totals.own.lines),
          num(totals.own.nonBlank),
        ],
        [
          totals.grand.label,
          num(totals.grand.files),
          num(totals.grand.lines),
          num(totals.grand.nonBlank),
        ],
        [
          totals.everything.label,
          num(totals.everything.files),
          totals.everything.linesKnown ? num(totals.everything.lines) : `${num(totals.everything.lines)} (text rows only)`,
          totals.everything.linesKnown
            ? num(totals.everything.nonBlank)
            : `${num(totals.everything.nonBlank)} (text rows only)`,
        ],
      ],
    ),
  );
  out.push('');

  out.push('#### Authorship — surviving lines');
  out.push('');
  out.push(
    'Attributed per surviving line with `git blame`, not by summing added lines from the log: a line written and later deleted belongs to nobody.',
  );
  out.push('');
  out.push(
    `Rule used: a commit counts as **agent-authored** when its author name or email matches \`${AGENT_IDENTITY_RE.source}\` (case-insensitive), ` +
      'or when its message carries a `Co-Authored-By:` trailer whose value matches the same pattern. Every other commit counts as human-authored. ' +
      'Lines present in the working tree but not yet committed are reported on their own row.',
  );
  out.push('');
  if (!attribution.computed) {
    out.push(
      mdTable(
        ['Authorship', 'Lines', 'Share'],
        ['l', 'r', 'r'],
        [['Agent-authored', 'not computed', '—'], ['Human-authored', 'not computed', '—']],
      ),
    );
    out.push('');
    out.push('Re-run with `--blame` (optionally `--blame-paths <globs>`) to compute it.');
  } else {
    const rows = [
      ['Agent-authored', num(attribution.agent), share(attribution.agent, attribution.lines)],
      ['Human-authored', num(attribution.human), share(attribution.human, attribution.lines)],
    ];
    if (attribution.uncommitted > 0) {
      rows.push([
        'Uncommitted (working tree)',
        num(attribution.uncommitted),
        share(attribution.uncommitted, attribution.lines),
      ]);
    }
    if (attribution.unclassified > 0) {
      rows.push([
        'Unclassified commit',
        num(attribution.unclassified),
        share(attribution.unclassified, attribution.lines),
      ]);
    }
    rows.push([
      '**Total attributed**',
      `**${num(attribution.lines)}**`,
      `**${share(attribution.lines, attribution.lines)}**`,
    ]);
    out.push(mdTable(['Authorship', 'Lines', 'Share'], ['l', 'r', 'r'], rows));
    out.push('');
    out.push(
      `Scope: ${attribution.scope} — ${num(attribution.files)} file(s). The attributed total equals the counted line total for that same scope.`,
    );
  }
  out.push('');

  out.push('#### Reproduce');
  out.push('');
  out.push('```');
  out.push(meta.command);
  out.push('```');
  out.push('');
  out.push(
    'Counts every tracked file exactly once: each scope table sums to its own total, and every excluded path is a visible row above.',
  );
  if (report.uncategorized.length > 0) {
    out.push('');
    out.push(
      `${num(report.uncategorized.length)} file(s) landed in the catch-all \`Uncategorized\` row; run with \`--json\` to list them.`,
    );
  }
  return out.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const argv = process.argv.slice(2);
  const opts = parseArgs(argv);
  if (opts.help) {
    process.stdout.write(`${HELP}\n`);
    return;
  }

  let repoRoot;
  try {
    repoRoot = git(['rev-parse', '--show-toplevel'], { cwd: process.cwd() }).trim();
  } catch {
    fail('not inside a git repository (git rev-parse --show-toplevel failed)');
  }

  let scriptRel = SCRIPT_REL_FALLBACK;
  try {
    scriptRel = path.relative(repoRoot, fileURLToPath(import.meta.url)).split(path.sep).join('/');
  } catch {
    // Keep the fallback; the reproduce line stays correct for a repo-root run.
  }
  const command = ['node', scriptRel, ...argv].join(' ');

  let commit = '';
  let commitShort = '';
  try {
    commit = git(['rev-parse', 'HEAD'], { cwd: repoRoot }).trim();
    commitShort = commit.slice(0, 7);
  } catch {
    commit = '';
    commitShort = '(no commit yet)';
  }
  let workingTreeDirty = false;
  try {
    workingTreeDirty = git(['status', '--porcelain'], { cwd: repoRoot }).trim().length > 0;
  } catch {
    workingTreeDirty = false;
  }

  const entries = listTrackedFiles(repoRoot);
  const { rows, areas, excluded, counted, uncategorizedPaths } = collect(repoRoot, entries);

  // Self-check: every tracked file is either a counted row or an excluded row.
  const countedFiles = sum(rows).files;
  const excludedFiles = excluded.reduce((n, r) => n + r.files, 0);
  if (countedFiles + excludedFiles !== entries.length) {
    fail(
      `internal accounting error: ${num(entries.length)} tracked file(s) but ${num(countedFiles)} counted + ` +
        `${num(excludedFiles)} excluded = ${num(countedFiles + excludedFiles)}. A bucketing that loses files is a misrepresentation; ` +
        'fix the classifier rather than publishing the number.',
      1,
    );
  }

  // Build the reported scopes: this repository's own code first, then each
  // imported upstream tree.
  const scopes = [];
  const ownRows = rows.filter((r) => r.scope === '');
  scopes.push({
    key: 'own',
    prefix: '',
    label: "This repository's own code",
    rows: ownRows,
    areas: areas.filter((a) => a.scope === ''),
    totals: sum(ownRows),
  });
  for (const upstream of UPSTREAM_PREFIXES) {
    const scopeRows = rows.filter((r) => r.scope === upstream.prefix);
    if (scopeRows.length === 0) continue;
    scopes.push({
      key: upstream.prefix,
      prefix: upstream.prefix,
      label: upstream.label,
      rows: scopeRows,
      areas: areas.filter((a) => a.scope === upstream.prefix),
      totals: sum(scopeRows),
    });
  }

  // Every scope table carries the mandatory catch-all row, even at zero, so a
  // reader can see that nothing was dropped.
  for (const scope of scopes) {
    if (!scope.rows.some((r) => r.category === 'Uncategorized')) {
      scope.rows.push({ scope: scope.prefix, category: 'Uncategorized', kind: '—', files: 0, lines: 0, nonBlank: 0 });
    }
  }

  const grand = sum(rows);
  const own = sum(ownRows);
  const excludedKnown = excluded.filter((r) => r.linesKnown);
  const excludedLines = excludedKnown.reduce((n, r) => n + r.lines, 0);
  const excludedNonBlank = excludedKnown.reduce((n, r) => n + r.nonBlank, 0);

  const totals = {
    own: {
      label: "Project's own code (everything tracked outside the imported upstream tree)",
      files: own.files,
      lines: own.lines,
      nonBlank: own.nonBlank,
    },
    grand: {
      label: 'Grand total counted (own code + imported upstream tree)',
      files: grand.files,
      lines: grand.lines,
      nonBlank: grand.nonBlank,
    },
    everything: {
      label: 'All tracked files, including the excluded rows above',
      files: grand.files + excludedFiles,
      lines: grand.lines + excludedLines,
      nonBlank: grand.nonBlank + excludedNonBlank,
      // Binary, symlink and gitlink rows have no line count, so the figure covers
      // the text rows only. Said plainly rather than implied.
      linesKnown: excluded.every((r) => r.linesKnown),
    },
  };

  let attribution = { computed: false };
  if (opts.blame) {
    const matcher = buildPathMatcher(opts.blamePaths);
    attribution = attribute(repoRoot, counted, matcher);
  }

  const report = {
    meta: {
      command,
      commit,
      commitShort,
      workingTreeDirty,
      trackedFiles: entries.length,
      discovery: 'git ls-files',
    },
    scopes: scopes.map((s) => ({
      key: s.key,
      label: s.label,
      prefix: s.prefix,
      rows: sortRows(s.rows).map((r) => ({
        category: r.category,
        kind: r.kind,
        files: r.files,
        lines: r.lines,
        nonBlank: r.nonBlank,
      })),
      areas: [...s.areas]
        .sort((a, b) => (b.lines !== a.lines ? b.lines - a.lines : a.area.localeCompare(b.area)))
        .map((a) => ({ area: a.area, files: a.files, lines: a.lines, nonBlank: a.nonBlank })),
      total: sum(s.rows),
    })),
    excluded: excluded
      .map((r) => ({
        reason: r.reason,
        files: r.files,
        lines: r.linesKnown ? r.lines : null,
        nonBlank: r.linesKnown ? r.nonBlank : null,
        linesKnown: r.linesKnown,
        examples: r.examples,
      }))
      .sort((a, b) => b.files - a.files),
    totals,
    attribution: {
      ...attribution,
      rule:
        'agent-authored when the commit author name or email matches the automation pattern, or the commit message carries a ' +
        'Co-Authored-By trailer naming an agent; every other commit is human-authored',
      pattern: AGENT_IDENTITY_RE.source,
    },
    uncategorized: uncategorizedPaths,
  };

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
  } else {
    process.stdout.write(`${renderMarkdown(report)}\n`);
  }
}

try {
  main();
} catch (err) {
  fail(err && err.stack ? err.stack : String(err), 1);
}
