[CmdletBinding()]
param()
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'ui-drive-test-fixture.ps1')
$sourceRoot=Split-Path $PSScriptRoot -Parent;$tempRoot=Join-Path ([IO.Path]::GetTempPath()) ('material-designer-live-origin-'+[guid]::NewGuid().ToString('N'));$redCount=0
function Invoke-Structural($f,[switch]$Promotion){$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $f.RepositoryRoot 'scripts/validate-ui-drive-receipt.ps1'),'-Receipt',$f.Receipt,'-Inventory',$f.Inventory,'-SceneRegistry',$f.Registry,'-Authority',$f.Authority,'-EvidenceRoot',$f.EvidenceRoot,'-RepositoryRoot',$f.RepositoryRoot);if(-not$Promotion){$args+='-StructuralOnly'};$p=$ErrorActionPreference;try{$ErrorActionPreference='Continue';&powershell.exe @args 1>$null 2>$null;return $LASTEXITCODE}finally{$ErrorActionPreference=$p}}
function Expect-Red([string]$name,[scriptblock]$action){$code=&$action;if($code-eq0){throw "Live-origin negative '$name' stayed green."};$script:redCount++;Write-Output "RED: $name"}
function Rebind-Chain($f){
    $origin=Get-Content -Raw $f.Origin|ConvertFrom-Json;$transcriptHash=(Get-FileHash $f.Transcript -Algorithm SHA256).Hash.ToLowerInvariant();$origin.transcriptSha256=$transcriptHash;Write-UITestJson $origin $f.Origin;$originHash=(Get-FileHash $f.Origin -Algorithm SHA256).Hash.ToLowerInvariant()
    $receipt=Get-Content -Raw $f.Receipt|ConvertFrom-Json;$receipt.liveOrigin.sha256=$originHash;Write-UITestJson $receipt $f.Receipt;$receiptHash=(Get-FileHash $f.Receipt -Algorithm SHA256).Hash.ToLowerInvariant()
    $manifest=Get-Content -Raw $f.Manifest|ConvertFrom-Json;($manifest.entries|Where-Object kind -eq 'driver-transcript').sha256=$transcriptHash;($manifest.entries|Where-Object kind -eq 'driver-transcript').bytes=[int64](Get-Item $f.Transcript).Length;($manifest.entries|Where-Object kind -eq 'live-origin').sha256=$originHash;($manifest.entries|Where-Object kind -eq 'live-origin').bytes=[int64](Get-Item $f.Origin).Length;($manifest.entries|Where-Object kind -eq 'receipt').sha256=$receiptHash;($manifest.entries|Where-Object kind -eq 'receipt').bytes=[int64](Get-Item $f.Receipt).Length;Write-UITestJson $manifest $f.Manifest
}
function Mutate-OriginRed($f,[string]$name,[scriptblock]$mutation){$paths=@($f.Origin,$f.Transcript,$f.Receipt,$f.Manifest);$backups=@{};foreach($p in $paths){$backups[$p]=[IO.File]::ReadAllBytes($p)};try{$origin=Get-Content -Raw $f.Origin|ConvertFrom-Json;&$mutation $origin;Write-UITestJson $origin $f.Origin;Rebind-Chain $f;Expect-Red $name {Invoke-Structural $f}}finally{foreach($p in $paths){[IO.File]::WriteAllBytes($p,$backups[$p])}}}
try{
    $f=New-UIEvidenceTestRepository -SourceRoot $sourceRoot -DestinationRoot $tempRoot
    if((Invoke-Structural $f)-ne0){throw 'Structural fixture baseline is not valid.'}
    Expect-Red 'manual-fixture-cannot-promote' {Invoke-Structural $f -Promotion}
    Mutate-OriginRed $f 'replayed-origin-key' {param($o)$o.replayKey='5555555555555555555555555555555555555555555555555555555555555555'}
    Mutate-OriginRed $f 'old-image-time' {param($o)$o.startedAtUtc='2026-08-30T00:00:00.0000000Z';$o.completedAtUtc='2026-08-30T00:00:01.0000000Z'}
    $originalTime=(Get-Item $f.Image).LastWriteTimeUtc;try{(Get-Item $f.Image).LastWriteTimeUtc=$originalTime.AddMinutes(1);Expect-Red 'touched-image-timestamp' {Invoke-Structural $f}}finally{(Get-Item $f.Image).LastWriteTimeUtc=$originalTime}
    Mutate-OriginRed $f 'wrong-process-image' {param($o)$o.processImageSha256='6666666666666666666666666666666666666666666666666666666666666666'}
    Mutate-OriginRed $f 'wrong-window-title' {param($o)$o.windowTitle='Wrong window'}
    Mutate-OriginRed $f 'wrong-action' {param($o)$o.actionKind='keyboard'}
    Mutate-OriginRed $f 'wrong-semantic-poll' {param($o)$o.semanticPolls[0].observedState='wrong state'}
    Mutate-OriginRed $f 'wrong-driver-executable' {param($o)$o.driverExecutableSha256='7777777777777777777777777777777777777777777777777777777777777777'}
    Mutate-OriginRed $f 'json-capability-field' {param($o)$o.PSObject.Properties.Add([psnoteproperty]::new('capability','serialized'))}
    $paths=@($f.Origin,$f.Transcript,$f.Receipt,$f.Manifest);$backups=@{};foreach($p in $paths){$backups[$p]=[IO.File]::ReadAllBytes($p)};try{$t=Get-Content -Raw $f.Transcript|ConvertFrom-Json;$t.calls[0].nonceDigest='8888888888888888888888888888888888888888888888888888888888888888';Write-UITestJson $t $f.Transcript;Rebind-Chain $f;Expect-Red 'self-authored-transcript-wrong-nonce' {Invoke-Structural $f}}finally{foreach($p in $paths){[IO.File]::WriteAllBytes($p,$backups[$p])}}
    $ledgerHash=(Get-FileHash (Join-Path $sourceRoot '.codex/verification/ui-drive/ledger.json') -Algorithm SHA256).Hash;$old=$env:UI_DRIVE_CAPABILITY_JSON;try{$env:UI_DRIVE_CAPABILITY_JSON='{"capability":"manual"}';$output=&powershell.exe -NoProfile -ExecutionPolicy Bypass -File (Join-Path $sourceRoot 'scripts/run-approved-ui-drive-live.ps1') -SceneId 'scene-windows-desktop-application-language-modes-change-language-mode';if($LASTEXITCODE-ne0-or($output-join'')-notmatch '"driverInvoked":false'){throw 'Manual environment no-row route did not remain structural-only.'}}finally{$env:UI_DRIVE_CAPABILITY_JSON=$old};if((Get-FileHash (Join-Path $sourceRoot '.codex/verification/ui-drive/ledger.json') -Algorithm SHA256).Hash-cne$ledgerHash){throw 'Manual environment changed the real ledger.'};$redCount++;Write-Output 'RED: manual-environment-capability-ignored'
    $sourceVerifier=Join-Path $sourceRoot 'scripts/verify-ui-drive-live-origin-source.ps1';&powershell.exe -NoProfile -ExecutionPolicy Bypass -File $sourceVerifier 1>$null;if($LASTEXITCODE-ne0){throw 'Live-origin source baseline is red.'}
    foreach($case in @([pscustomobject]@{name='detached-production-import';path=(Join-Path $sourceRoot 'scripts/run-approved-ui-drive-live.ps1');needle='Import-Module $modulePath -Force -ErrorAction Stop'},[pscustomobject]@{name='detached-production-call';path=(Join-Path $sourceRoot 'scripts/run-approved-ui-drive-live.ps1');needle='$result=Invoke-UIApprovedLiveCapture'},[pscustomobject]@{name='detached-fixed-driver-bridge';path=(Join-Path $sourceRoot 'scripts/ui-drive-lowlevel-stdin-bridge.ps1');needle='GitHub/lowlevel-computer-use-mcp/.venv/Scripts/lowlevel-computer-use-cheap.exe'})){
        $copy=Join-Path $tempRoot ([IO.Path]::GetFileNameWithoutExtension($case.path)+'-'+$case.name+[IO.Path]::GetExtension($case.path));$text=[IO.File]::ReadAllText($case.path);$changed=$text.Replace($case.needle,'# detached');if($changed-ceq$text){throw 'Source detachment mutation did not land.'};[IO.File]::WriteAllText($copy,$changed,[Text.UTF8Encoding]::new($false));$args=@('-NoProfile','-ExecutionPolicy','Bypass','-File',$sourceVerifier);if($case.path-like'*run-approved*'){$args+=@('-Orchestrator',$copy)}else{$args+=@('-Bridge',$copy)};$p=$ErrorActionPreference;try{$ErrorActionPreference='Continue';&powershell.exe @args 1>$null 2>$null;$code=$LASTEXITCODE}finally{$ErrorActionPreference=$p};if($code-eq0){throw "Source negative '$($case.name)' stayed green."};$redCount++;Write-Output "RED: $($case.name)"
    }
    Write-Output "PASS: $redCount live-origin promotion, replay, freshness, process, window, action, poll, nonce, executable, capability, environment, and source-detachment negatives turned red; no live driver ran."
}finally{if(Test-Path $tempRoot){$resolved=[IO.Path]::GetFullPath($tempRoot);if(-not$resolved.StartsWith([IO.Path]::GetFullPath([IO.Path]::GetTempPath()),[StringComparison]::OrdinalIgnoreCase)){throw 'Unexpected live-origin fixture path.'};Get-ChildItem $resolved -Recurse -Force|ForEach-Object{[IO.File]::SetAttributes($_.FullName,[IO.FileAttributes]::Normal)};[IO.Directory]::Delete($resolved,$true)}}
